package com.hk.pojo;

import java.util.Date;

public class user2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.favorite
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String favorite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.goods
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private Integer goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isAdmin
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private Integer isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.favorite
     *
     * @return the value of user.favorite
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getFavorite() {
        return favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.favorite
     *
     * @param favorite the value for user.favorite
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setFavorite(String favorite) {
        this.favorite = favorite == null ? null : favorite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school
     *
     * @return the value of user.school
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school
     *
     * @param school the value for user.school
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.goods
     *
     * @return the value of user.goods
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.goods
     *
     * @param goods the value for user.goods
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isAdmin
     *
     * @return the value of user.isAdmin
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isAdmin
     *
     * @param isadmin the value for user.isAdmin
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}