package com.hk.dao;

import com.hk.pojo.user2;
import com.hk.pojo.user2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface user2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    long countByExample(user2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int deleteByExample(user2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int insert(user2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int insertSelective(user2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    List<user2> selectByExample(user2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    user2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int updateByExampleSelective(@Param("row") user2 row, @Param("example") user2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int updateByExample(@Param("row") user2 row, @Param("example") user2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int updateByPrimaryKeySelective(user2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jun 13 23:38:21 CST 2022
     */
    int updateByPrimaryKey(user2 row);
}